
name: Test

on: push
jobs:
  test:
    name: Run Test
    runs-on: ubuntu-latest
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      DBOCID: ${{ secrets.DBOCID }}
      DBPWD: ${{ secrets.DB_WALLET_PASSWORD }}
    steps:
      - name: Retrieve the OCID of a named compartment in tenancy
        run: |-
          echo "Push!"
