
name: Run Test

on:
  push:
    branches:
      - 'main'

jobs:
  prep_matrix:
    name: Run Prep
    runs-on: ubuntu-latest
    outputs:
      schemas: ${{ steps.getschemas.outputs.schemas }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: list
      id: getschemas
      run: echo "schemas=$(python scripts/run_util.py schemas liquibase)" >> "$GITHUB_OUTPUT"
      
  test_push:
    name: Run command
    runs-on: ubuntu-latest
    needs: [prep_matrix]
    strategy:
      matrix:
        schemas: ${{ fromJson(needs.prep_matrix.outputs.schemas) }}

    steps:
    - name: List
      run: echo ${{ matrix.schemas }}